# example configuration file

[eg]
host = "localhost"
sysDB = "postgres"
database = "bluefin_example"
migrations = "migrations"
middleware = ["transactions"]

[eg.roles]
color = "settings/create.sql"
pbp = "settings/create.sql"

[eg.grants]
color = "settings/read.sql"
pbp = ["settings/read.sql", "settings/write.sql"]

[eg.env]
foo = "bar"
nurp = "plonk"
